[package]
name = "gitrs"
version = "0.1.0"
authors = ["langnostic <jfitzy1321@pm.me>"]
repository = "https://github.com/langnostic/gitrs"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.*"